config/routes.rb
MyResume::Application.routes.draw do
	
  root 'welcome#index'

  match "/send_email", to: "welcome#send_email", via: "post"

   

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  	def index
  	
  	end

  	def send_email()
  		unless params[:email].empty? && params[:msg].empty?		
			UserMailer.send_email(params[:email], params[:msg],).deliver
			flash[:success] = "Ваше сообщение отправлено на мой email!"
		else
			flash[:error] = "Ваше сообщение не отправлено! Возможно заполнены не все поля."
		end
		redirect_to root_path

  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyResume</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/_div_contact_me.html.erb
<div id="id_div_wrapper_window_contact_me">

	<div class="class_div_darkening_background_for_window_contact_me"></div>

	<div class="class_div_window_contact_me">

		<div id="id_bt_close_in_window_contact_me">Закрыть</div>

		<div class="class_div_content_in_window_contact_me">
			<div id="id_div_my_contacts">
				<p><h3>Email:</h3> rwr_pavel@mail.ru</p>
				<p><h3>Skype:</h3> Hazius</p>
			</div>
			<div id="id_div_form_send_email">
				<h3>Отправить мне письмо на почту:</h3>			
				<%= render "form_send_email" %>	
			</div>		
		</div>

	</div>

</div>

app/views/welcome/_form_send_email.html.erb
<%= form_tag(send_email_path, method: "post") do %>
	Ваш email:<br>
	<%= email_field_tag(:email, nil, placeholder: "Введите свой Email") %><br>
	Текст сообщения:<br>
	<%= text_area_tag(:msg, nil, cols: "40", rows: "10") %><br>
	<%= submit_tag("Отправить") %>
<% end %>

app/views/welcome/index.html.erb
<%= render "div_contact_me" %>

<div id="id_div_wrapper">

	<br>

	<% flash.each do |key, value| %>
		<h1 class="class_message_<%= key %>"><%= value %></h1>
	<% end %>	

	<br>

	<div id="id_my_information">	

		<div id="id_short_about_me">
			<h2>Hazius (Павел)</h2>		
			<p>Возраст: <%= Time.now.year.to_i - 1990 %> года.</p>
			<%= image_tag("my_foto.jpg", html_options = { class: "class_my_foto" } ) %>		
		</div>

		<%= image_tag("bt_contact_me.png", html_options = { id: "id_bt_contact_me" }) %>			

		<div class="class_clear"></div>

	</div>

	<div id="id_div_desired_rate">		
		<!-- <h2>Желаемый рейт: р/час</h2> -->
	</div>

	<div id="id_div_skills">
		<ul>	
			<li>Образование: законченное высшее (профильное):<br>"Автоматизированные системы управления"</li>
			<li>Используемая ОС: Ubuntu</li>	
			<li>English: уровень Pre-Intermediate</li>		
			<li>Ruby on Rails</li>	
			<li>HTML</li>
			<li>SCSS</li>
			<li>JS и jQuery</li>
			<li>AJAX</li>
			<li>RSpec+Capybara</li>
			<li>Git+GitHub</li>
			<li>C#</li>	
		</ul>
		<h2><%= link_to("GitHub", "https://github.com/Hazius") %></h2>
		<br>
		<h2>Задеплоинные приложения на Heroku:</h2>
		<ul>
			<li><%= link_to("Calculator for exchange", "https://calculator-for-exchange.herokuapp.com") %>
			<br>(простая реализация формулы)</li>
			<li><%= link_to("Blog from hazius", "https://blog-from-hazius.herokuapp.com") %>
			<br>(движок блога с механизмом аутентификации и авторизации)</li>
		</ul>
		
	</div>

	<div class="class_clear"></div>

	<div id="id_div_story_about_me">
		<h2>Моя история:</h2>
		<ul>

			<li>1) C#.<br>
					6 месяцев разработок (и доведения до конца) двух клиент-серверных приложения на С#:<br>
					- Сетевая игра в шашки<br>
					- Приложение по тестированию знананий с отправкой серверу результатов<br>
					Итог: очень интересовало, но дальнейшую работу не нашел.<br>
			</li>

			<li>2) PHP.<br>
					Пару недель мучал php. После "dot net" пришел к выводу, что кодинг на php это не мое.
			</li>			

			<li>3) ABAP (SAP).<br>		
					Работаю с 01.02.13 по настоящее время...
					Вещь очень специфичная. Как я понимаю, одна из самых оплачиваемых в отрасли кодинга...<br>
					Все бы ничего, но это ОЧЕНЬ скучная, нудная и мало творческая работа.<br> 
					Карьерные перспективы определенно есть. Но душа не лежит. Не моя мечта как программиста.<br>
					Я думаю со мной разделят данную точку зрения многие, программирующие на ABAP под задачи SAP...
			</li>

			<li>4) И вот, наконец, мы подобрались к RoR.<br>
					Активно изучаю 5 месяцев. 
			</li>

		</ul>

	</div>

	<br><br>

</div>